"""
Generate hyperbolic {p,q} regular tiling data as C header file.
Sphere scale = 30 to match polyhedra visual size.
"""
import math, sys, os

def g(a, b):
    return a[0]*b[0] - a[1]*b[1] - a[2]*b[2]

def cross_m(v, w):
    return (v[1]*w[2] - v[2]*w[1],
            v[0]*w[2] - v[2]*w[0],
           -v[0]*w[1] + v[1]*w[0])

def make_reflection(N):
    nn = g(N, N)
    if abs(nn) < 1e-12: return None
    def reflect(X):
        t = 2 * g(X, N) / nn
        return tuple(X[i] - t * N[i] for i in range(3))
    return reflect

def generate_tiling(p, q, max_gen):
    coshR = math.cos(math.pi / p) / math.sin(math.pi / q)
    R = math.acosh(coshR)
    sinhR = math.sinh(R)
    center_v = [(coshR, sinhR * math.cos(2*math.pi*k/p), sinhR * math.sin(2*math.pi*k/p)) for k in range(p)]
    edge_refl = [make_reflection(cross_m(center_v[k], center_v[(k+1)%p])) for k in range(p)]

    all_verts = {tuple(round(c,10) for c in v): i for i,v in enumerate(center_v)}
    vert_list = list(center_v)
    edges_set = set(tuple(sorted((k, (k+1)%p))) for k in range(p))

    queue = [(i, edge_refl[i]) for i in range(p)]
    for gen in range(1, max_gen):
        nq = []
        for last_idx, reflection in queue:
            new_v = [reflection(v) for v in center_v]
            idxs = []
            for v in new_v:
                key = tuple(round(c,10) for c in v)
                if key not in all_verts:
                    all_verts[key] = len(vert_list)
                    vert_list.append(v)
                idxs.append(all_verts[key])
            for k in range(p):
                edges_set.add(tuple(sorted((idxs[k], idxs[(k+1)%p]))))
            for i in range(p):
                if i == last_idx:
                    continue
                ri = edge_refl[i]
                nq.append((i, lambda X, ri=ri, old=reflection: ri(old(X))))
        queue = nq
    return vert_list, sorted(edges_set)

SPHERE_SCALE = 30.0

def to_sphere(X):
    pd_x = X[1] / (1 + X[0])
    pd_y = X[2] / (1 + X[0])
    r2 = pd_x*pd_x + pd_y*pd_y
    if r2 >= 0.99: return None
    d = 1 + r2
    return (SPHERE_SCALE*2*pd_x/d, SPHERE_SCALE*2*pd_y/d, SPHERE_SCALE*(1-r2)/d)

# Tilings: (p, q, gen, label)
TILINGS = [
    (3, 7, 3, "H3_7"),
    (3, 8, 3, "H3_8"),
    (4, 5, 3, "H4_5"),
    (5, 4, 3, "H5_4"),
    (4, 6, 3, "H4_6"),
    (6, 4, 3, "H6_4"),
    (5, 5, 3, "H5_5"),
    (5, 6, 3, "H5_6"),
    (6, 5, 3, "H6_5"),
    (7, 3, 2, "H7_3"),
    (8, 3, 2, "H8_3"),
    (3, 10, 3, "H3_10"),
    (10, 3, 2, "H10_3"),
]

# Generate
output_path = os.path.join(os.path.dirname(__file__), "..", "Hardware", "Cube3D_Hyperbolic.h")
output_path = os.path.normpath(output_path)

with open(output_path, "w") as f:
    f.write("/* Auto-generated by Tools/gen_hyperbolic.py */\n")
    f.write("#ifndef __CUBE3D_HYPERBOLIC_H\n#define __CUBE3D_HYPERBOLIC_H\n\n")
    f.write('#include "Cube3D.h"\n\n')

    max_v = 0
    total_b = 0

    for p, q, gen, label in TILINGS:
        verts, edges = generate_tiling(p, q, gen)
        sphere_v = [to_sphere(v) for v in verts if to_sphere(v)]
        nv = len(sphere_v)
        ne = len(edges)
        max_v = max(max_v, nv)
        vb = nv * 3 * 4
        eb = ne * 2
        total_b += vb + eb

        f.write(f"/* {{{p},{q}}} gen={gen}: {nv} verts, {ne} edges, ~{vb+eb}B */\n")
        f.write(f"#define {label}_VTX_COUNT  {nv}\n")
        f.write(f"#define {label}_EDGE_COUNT {ne}\n\n")
        f.write(f"static const Vec3f_t k{label}Vertices[{label}_VTX_COUNT] =\n{{\n")
        for s in sphere_v:
            f.write(f"\t{{{s[0]:.6f}f, {s[1]:.6f}f, {s[2]:.6f}f}},\n")
        f.write("};\n\n")
        f.write(f"static const uint8_t k{label}Edges[{label}_EDGE_COUNT][2] =\n{{\n")
        for v1, v2 in edges:
            f.write(f"\t{{{v1}, {v2}}},\n")
        f.write("};\n\n")

    f.write(f"/* MAX_VTX = {max_v} */\n")
    f.write(f"#define HYPERBOLIC_MAX_VTX {max_v}\n\n")
    f.write(f"/* Total Flash: ~{total_b} bytes */\n")
    f.write("#endif\n")

    print(f"Generated {output_path}")
    print(f"  {len(TILINGS)} tilings, max {max_v} verts, ~{total_b} bytes")
    print(f"  Shapes: {[l for _,_,_,l in TILINGS]}")
